ecm0-carrier: contribute the meta-ecm
edgeble/contribute pull request #2
Opened 2022-08-04 16:18 UTC by moonlinux

Guideline to help push the changes to remote repository

2022-08-04 16:38 UTC, openedev requested changes

2022-08-04 16:38 UTC, openedev commented on README.md
> +
code snippet
```shell
sudo apt install gh
```

2022-08-04 16:39 UTC, openedev commented on README.md
> +
all the places where code we need to enclose the prefix ```shell and ``` suffix

2022-08-04 17:51 UTC, moonlinux commented on README.md
> +
ok

2022-08-05 08:43 UTC, openedev approved these changes

2022-08-05 08:43 UTC, merged